val userA = readLine("Enter first User(id)  : ")
val userB = readLine("Enter second User(id) : ")
val fileInput = sc.textFile("hdfs://cshadoop1/socNetData/networkdata")
val friendA = fileInput.map(li=>li.split("\\t")).filter(l1 => (l1.size == 2)).filter(li=>(userB==li(0))).flatMap(li=>li(1).split(","))
val friendB = fileInput.map(li=>li.split("\\t")).filter(l1 => (l1.size == 2)).filter(li=>(userA==li(0))).flatMap(li=>li(1).split(","))
val mutualFriendsList = friendB.intersection(friendA).collect()
val output = userA+", "+userB+"\t"+mutualFriendsList.mkString(",")
print(output)
System.exit(0)
